### ISSUE TITLE
Convert from colons to spaces for command syntax

### ISSUE THREAD

**Issue by zstumgoren** [associatedpress/datakit-data#16]
Turns out the use of colons to namespace plugin commands (in setup.py `entry_points`) was a poor design decision, since colons are one of the default delimiters used by ConfigParser (which in turn is used during pip installation of source distributions). This has caused a non-fatal but disconcerting configuration error during pip installation of the library (see stack trace below).

After discussing with AP teammates, have agreed to simply swap in spaces for the colons in the commands to address the issue. May also create additional natural language command aliases in the future, but planning to start with the simple `:` -> `\s` migration for now.

## Stacktrace

Below error is generated when pip installing datakit-data:

```
Installing collected packages: datakit-data
Exception:
Traceback (most recent call last):
  File "/Users/stumgoren/.pyenv/versions/3.5.1/envs/datakit-test/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/stumgoren/.pyenv/versions/3.5.1/envs/datakit-test/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Users/stumgoren/.pyenv/versions/3.5.1/envs/datakit-test/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Users/stumgoren/.pyenv/versions/3.5.1/envs/datakit-test/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Users/stumgoren/.pyenv/versions/3.5.1/envs/datakit-test/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Users/stumgoren/.pyenv/versions/3.5.1/envs/datakit-test/lib/python3.5/site-packages/pip/wheel.py", line 351, in move_wheel_files
    console, gui = get_entrypoints(ep_file)
  File "/Users/stumgoren/.pyenv/versions/3.5.1/envs/datakit-test/lib/python3.5/site-packages/pip/wheel.py", line 229, in get_entrypoints
    cp.readfp(data)
  File "/Users/stumgoren/.pyenv/versions/3.5.1/lib/python3.5/configparser.py", line 760, in readfp
    self.read_file(fp, source=filename)
  File "/Users/stumgoren/.pyenv/versions/3.5.1/lib/python3.5/configparser.py", line 715, in read_file
    self._read(f, source)
  File "/Users/stumgoren/.pyenv/versions/3.5.1/lib/python3.5/configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '<???>' [line  3]: option 'data' in section 'datakit.plugins' already exists
```

**Comment by zstumgoren** [comment]
* Updated code, docs and tests to reflect the new syntax
* Fixed Travis tests to use newer "matrix" api and run against wider range of Python 3 versions, including 3.6. 
* Open source docs are deployed to RTD
* Bumped version to `0.2.0`
